version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: web_nginx
    ports:
      - 80:80
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
