version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.249.1-lts-centos7
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
    environment:
       JENKINS_OPTS: '--prefix=/jenkins'
